---
- name: Run show version on cisco routers
  hosts: asr
  gather_facts: false
  connection: local

  tasks:
    - name: Running show version command
      ios_command:
        commands: show version
      register: output

    - name: show command output
      debug:
        var: output.stdout

